version: "3.9"
services:
  node:
    build:
      context: .
      dockerfile: ./infra/docker/node/Dockerfile
    working_dir: /opt/src
    command: [ "yarn", "run", "dev" ]
    volumes:
      - ./src:/opt/src
    ports:
      - 5173:5173
